### ISSUE TITLE
network: try UDP

### ISSUE THREAD

**Issue by pca006132** [switefaster/multi_pong#5]
TCP ping is high as f**k.

TODO:
- [x] Draft.
- [x] Test it.
- [x] Remove serde dependency for the UDP module. Pass Vec instead, and define our protocol header.
- [x] Reduce clone.
- [x] Move `server_listen` and `client_connect` from the `udp_remote` example to the UDP module.
- [x] Refactor the `PacketType` enum, into something more user friendly, and encode order requirement. (Ordered packet would discard old packets without sending them to the user.)
- [x] Better error handling, with less unwrap.

Presumably, this would take quite a bit of time... it would be best if someone can help out.

**Comment by pca006132** [comment]
A sketch of the design: https://github.com/switefaster/multi_pong/tree/udp

The only thing right now is that it builds. Not yet tested, and the design is not even finished yet.

There are a couple of design problems right now:
* It uses quite a lot of copy, but may not be too hard to fix.
* The sender and receiver share the sender mutex, so we cannot control the priority. (we should prioritize over sending ACK).
* The receiver would wait until it sends the ACK before receiving another packet, we should be able to solve that if we introduce another channel between the sender and receiver, just let the receiver put the ACK packet into the channel and proceed.
* The current ACK packet is just the original packet with a negative slot value, while this is simple it would increase the load of the serializer, we should be able to modify the `DataPacket<T>` to `DataPacket<Option<T>>` though.

**Comment by pca006132** [comment]
Overview of the protocol:

We consider two types of messages, reliable and unreliable. 
* For reliable messages, we want to make sure the message reaches the recipient. 
* For unreliable messages, we just throw it into UDP and hope for the best.
We would mainly discuss reliable messages, as implementation for unreliable is trivial.

Reliable transmission is done by adding an acknowledgment (ACK) message into our system.  If the sender did not receive ACK after the message timeout, it would resend the message. In order to avoid ACK being lost which may cause the receiver to receive the same message two times, we would also track the received packet in the receiver side to discard any duplicated message from the sender. This is implemented in both the sender and receiver by slot index and generation ID. We have *N* slots in both the sender and receiver side, each reliable message would be put into a slot, and it would get the slot ID and generation ID. Generation ID would only increment for different messages in the same slot. (it could wrap around, so we should do wrapped arithmetic)

When the sender sends a reliable message, it would first wait for an empty slot, store it into the slot and attach the slot ID and generation ID, and at last send it through UDP. If it receives the ACK from the receiver, it would first check if the ACK generation matches the stored packet, and empty the slot if yes.

When the receiver receives the message, it would first send the ACK. Afterward, it would check if the generation ID for that slot, and discard the message if the received one is not newer (received - stored > 0). If not, it would forward the packet to the application, and store the generation ID into that slot.

Currently, we implement the slot ID as isize, positive means message slot, negative means ACK slot, 0 means no ACK needed.

**Comment by switefaster** [comment]
In order to make the udp system("the system") more convenient to use, my suggestion is to add a trait, namely `PacketDesc` or something, which is tended to be implemented for an enum and will act as a generic boundary in the system, providing some useful information for packet management such as if the packet is reliable or not, the id of the packet which will be useful in discarding old(i.e. the generation is less than the generation we've received already) packets, and whether the packet should be discarded if it is old.
Following is a simple sketch:
```rust
pub trait PacketDesc {
    fn reliable(&self) -> bool;
    fn id(&self) -> u32;
    fn discard_old(&self) -> bool;
}

pub enum Packet {
    Reliable,
    UnreliableNoDiscard,
    UnreliableDiscard,
}

impl PacketDesc for Packet {
    fn reliable(&self) -> bool {
        match self {
            Reliable => true,
            _ => false,
        }
    }

    fn id(&self) -> u32 {
        match self {
            Reliable => 0,
            UnreliableNoDiscard => 1,
            UnreliableDiscard => 2,
        }
    }

    fn discard_old(&self) -> bool {
        match self {
            UnreliableDiscard => true,
            _ => false,
        }
    }
}
```
And it works better if we have a corresponding derive macro, ~~maybe we should create a multi_pong_derive crate then?~~

**Comment by pca006132** [comment]
> In order to make the udp system("the system") more convenient to use, my suggestion is to add a trait, namely `PacketDesc` or something, which is tended to be implemented for an enum and will act as a generic boundary in the system, providing some useful information for packet management such as if the packet is reliable or not, the id of the packet which will be useful in discarding old(i.e. the generation is less than the generation we've received already) packets, and whether the packet should be discarded if it is old.
> Following is a simple sketch:
> 
> ```rust
> pub trait PacketDesc {
>     fn reliable(&self) -> bool;
>     fn id(&self) -> u32;
>     fn discard_old(&self) -> bool;
> }
> 
> pub enum Packet {
>     Reliable,
>     UnreliableNoDiscard,
>     UnreliableDiscard,
> }
> 
> impl PacketDesc for Packet {
>     fn reliable(&self) -> bool {
>         match self {
>             Reliable => true,
>             _ => false,
>         }
>     }
> 
>     fn id(&self) -> u32 {
>         match self {
>             Reliable => 0,
>             UnreliableNoDiscard => 1,
>             UnreliableDiscard => 2,
>         }
>     }
> 
>     fn discard_old(&self) -> bool {
>         match self {
>             UnreliableDiscard => true,
>             _ => false,
>         }
>     }
> }
> ```
> 
> And it works better if we have a corresponding derive macro, ~maybe we should create a multi_pong_derive crate then?~

Done, have to see if the design is good to use.
