### ISSUE TITLE
Make click-to-run executable.

### ISSUE THREAD

**Issue by YijunYuan** [switefaster/multi_pong#8]
This program, as a game, should be more player-friendly.

**Comment by pca006132** [comment]
we are not even in alpha yet, would provide executable in release when it becomes more stable.

**Comment by switefaster** [comment]
ci support is scheduled to be available later. would appreciate it so much if you are willing to help us set it up

**Comment by YijunYuan** [comment]
> ci support is scheduled to be available later. would appreciate it so much if you are willing to help us set it up

I'm not interested

**Comment by pca006132** [comment]
Done via GitHub Action.
